version: '3'

services:
    laravel-nginx:
        build:
            context: ./docker/dev
            dockerfile: nginx.docker
        volumes:
            - ./laravel:/app
        ports:
            - "80:80"
        hostname: laravel
        domainname: laravel.loc
        networks:
            test:
                ipv4_address: 172.28.2.10

    laravel-php-fpm:
        build:
            context: ./docker/dev
            dockerfile: php-fpm.docker
        volumes:
            - ./laravel:/app
        networks:
            test:
                ipv4_address: 172.28.2.2

    laravel-php-cli:
        build:
            context: ./docker/dev
            dockerfile: php-cli.docker
        volumes:
            - ./laravel:/app
            - composer:/root/.composer/cache
        networks:
            test:
                ipv4_address: 172.28.2.3
    laravel-postgres:
        image: postgres:11.2-alpine
        volumes:
            - ./laravel-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "2345:5432"
        networks:
            test:
                ipv4_address: 172.28.2.4

#    laravel-node:
#        image: node:11-alpine
#        volumes:
#            - ./test-laravel:/app
#        working_dir: /app
#        networks:
#            test:
#                ipv4_address: 172.28.2.5
#
#    laravel-node-watch:
#        image: node:11-alpine
#        volumes:
#            - ./test-laravel:/app
#        working_dir: /app
#        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
#        networks:
#            test:
#                ipv4_address: 172.28.2.6

    laravel-mailer:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
        networks:
            test:
                ipv4_address: 172.28.2.15

volumes:
    laravel-postgres:
    composer:

networks:
    test:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16