version: '3'

services:
    app-nginx:
        build:
            context: ./docker/dev
            dockerfile: nginx.docker
        volumes:
            - ./app:/app
        ports:
            - "8088:80"
        hostname: laravel
        domainname: laravel.loc
        networks:
            test:
                ipv4_address: 172.28.2.10

    app-php-fpm:
        build:
            context: ./docker/dev
            dockerfile: php-fpm.docker
        volumes:
            - ./app:/app
        networks:
            test:
                ipv4_address: 172.28.2.2

    app-php-cli:
        build:
            context: ./docker/dev
            dockerfile: php-cli.docker
        volumes:
            - ./app:/app
            - composer:/root/.composer/cache
        networks:
            test:
                ipv4_address: 172.28.2.3
    app-postgres:
        image: postgres:11-alpine
        volumes:
            - ./app-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "2345:5432"
        networks:
            test:
                ipv4_address: 172.28.2.4

    app-node:
        image: node:11-alpine
        volumes:
            - ./app:/app
        working_dir: /app
        networks:
            test:
                ipv4_address: 172.28.2.5

    app-node-watch:
        image: node:11-alpine
        volumes:
            - ./app:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"
        networks:
            test:
                ipv4_address: 172.28.2.6

    app-mailer:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
        networks:
            test:
                ipv4_address: 172.28.2.15

volumes:
    app-postgres:
    composer:

networks:
    test:
        ipam:
            driver: default
            config:
                - subnet: 172.28.2.0/24